// <auto-generated />
using System;
using System.Collections.Generic;
using EffortlessInsight.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EffortlessInsight.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613120000_AddAdminPortalService")]
    partial class AddAdminPortalService
    {
    }
}
