services:
  db:
    image: pgvector/pgvector:pg16
    container_name: effortlessinsight-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arsteg@123
      POSTGRES_DB: effortlessinsight
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d effortlessinsight"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: effortlessinsight-redis
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
