using System.ComponentModel.DataAnnotations;

namespace EffortlessInsight.Api.Data.Entities;

/// <summary>
/// Well-known activity event types. The tracker accepts free-form types
/// (sanitized), but these are the ones the apps emit and the admin
/// analytics understand.
/// </summary>
public static class ActivityEventTypes
{
    public const string SessionStart = "session_start";
    public const string PageView = "page_view";
    public const string SignupStarted = "signup_started";
    public const string SignupMobileVerified = "signup_mobile_verified";
    public const string SignupCompleted = "signup_completed";
    public const string Login = "login";
    public const string Logout = "logout";
    public const string NoticeView = "notice_view";
    public const string Upload = "upload";
    public const string Search = "search";
    public const string Action = "action";
}

/// <summary>
/// One portal visitor — anonymous until they sign up or log in, at which
/// point <see cref="UserId"/> links their pre-signup activity to the
/// account. The VisitorId is a first-party random UUID generated by the
/// client (no fingerprinting, no third parties, no IP stored).
/// </summary>
public class Visitor : BaseEntity
{
    [Required]
    [MaxLength(64)]
    public string VisitorId { get; set; } = null!;

    /// <summary>Linked account once the visitor signs up / logs in.</summary>
    public Guid? UserId { get; set; }

    public DateTime? LinkedAt { get; set; }

    public DateTime FirstSeenAt { get; set; } = DateTime.UtcNow;

    public DateTime LastSeenAt { get; set; } = DateTime.UtcNow;

    /// <summary>Where the very first session came from (document.referrer).</summary>
    [MaxLength(500)]
    public string? FirstReferrer { get; set; }

    /// <summary>First page the visitor ever landed on.</summary>
    [MaxLength(300)]
    public string? LandingPage { get; set; }

    [MaxLength(300)]
    public string? UserAgent { get; set; }
}

/// <summary>
/// A single tracked activity event (page view, login, upload, …) for an
/// anonymous visitor or an authenticated user. Append-only and
/// deliberately lean — analytics queries always filter by CreatedAt range.
/// No passwords, tokens, document contents or free-text user input are
/// ever stored here.
/// </summary>
public class ActivityEvent : BaseEntity
{
    [Required]
    [MaxLength(64)]
    public string VisitorId { get; set; } = null!;

    /// <summary>Set when the event was sent by an authenticated user.</summary>
    public Guid? UserId { get; set; }

    /// <summary>Client-generated session id (rotates after 30 min idle).</summary>
    [Required]
    [MaxLength(64)]
    public string SessionId { get; set; } = null!;

    /// <summary>Sanitized snake_case type, e.g. page_view, login, upload.</summary>
    [Required]
    [MaxLength(50)]
    public string EventType { get; set; } = null!;

    /// <summary>Optional specific name, e.g. the button/action identifier.</summary>
    [MaxLength(150)]
    public string? EventName { get; set; }

    /// <summary>Route path only — never query strings (may carry PII).</summary>
    [MaxLength(300)]
    public string? Page { get; set; }

    [MaxLength(500)]
    public string? Referrer { get; set; }

    /// <summary>Related resource kind, e.g. notice, task, ticket.</summary>
    [MaxLength(50)]
    public string? EntityType { get; set; }

    public Guid? EntityId { get; set; }

    /// <summary>Small structured JSON payload (≤2000 chars, client-supplied).</summary>
    [MaxLength(2000)]
    public string? MetadataJson { get; set; }
}
